import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/app-sidebar";
import Navbar from "@/components/Navbar";
import AuthProvider from "@/components/providers/AuthProvider";
import { Toaster } from "@/components/ui/sonner";


const poppins = Poppins({
  weight: '400',
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body
        className={` ${poppins.className} antialiased`}
      >
        <AuthProvider>
          <SidebarProvider>
            <AppSidebar />
              <main className="w-full">
                <SidebarTrigger />
                <Navbar />
                {children}
              </main>
              <Toaster />
          </SidebarProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
